# Site settings
title: Hack Darmstadt 2017
email: info@hackdarmstadt.de
description: Hack Darmstadt, Civic Tech and LoRaWAN Hackathon for a better city
baseurl: ''
url: https://hackdarmstadt.de

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: hackdarmstadt
twitter_username: hackdarmstadt
facebook_URL:
instagram_username:

# Build settings
markdown: kramdown
